name: $(Build.SourceBranch)$(rev:.r)
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $v = ($env:BUILD_BUILDNUMBER)
      $v = $v.replace('refs_', '')
      $v = $v.replace('heads_', '')
      $v = $v.replace('releases_','')
      echo "##vso[task.setvariable variable=sauce;isOutput=true]12345" + $v 
      echo 'version has been set $v'
  name: 'SetVersionStep'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "$(SetVersionStep.sauce)"
- task: Npm@1
  inputs:
    command: 'install'